### ISSUE TITLE
not an issue, just a query

### ISSUE THREAD

**Issue by mattiLeBlanc** [pbastowski/meteor-typescript#2] opened 2016-02-03 22:33 UTC
Hi,

How would this work with Angular 1.4 + Meteor + typescript.
I have it running without the SystemJS following the tutorial on http://www.namekdev.net/2015/11/beginning-with-meteor-and-angularjs-on-top-of-typescript/.

Any benefit of adding SystemJS? I would like to import other classes like I do with my other non Meteor Typescript apps. Not sure if this makes that happen?

Also, is it an idea to put a little skeleton app in your github as an example. Maybe with and without Angular 1.4?

**Comment by pbastowski** [comment] 2016-02-06 06:40
Hi @mattiLeBlanc 

I use TypeScript with Meteor and Angular 1.4 (angular-meteor). The benefit being that I can import my classes, as per what you described in your question.

My TypeScript package creates SystemJS modules, by default. You can override this behaviour and compile to, say, commonjs or even no module wrapper at all. However, you were asking about SystemJS. So, by default, if you use my TypeScript package you will also want to use my SystemJS package.

To do this add the following packages to your project:

``` bash
meteor add pbastowski:typescript
meteor add pbastowski:systemjs
```

Then, follow the guide here [TypeScript With SystemJS](https://github.com/pbastowski/meteor-typescript#with-systemjs).

Your TS files will be registered with SystemJS by their path name relative to the project root. So, `client/app.ts` will be available as an import using this statement `import { XYZ } from 'client/app'`.

A little skeleton would be nice, I agree. Hopefully, the guide at the link above will be enough for now. If not then let me know and I can help you. If I find some time, I will add the skeleton. 

It might also be helpful for you to see how SystemJS is used with my [Babel](https://github.com/pbastowski/angular-meteor-babel/tree/meteor1.2#systemjs) package. There is a longer discussion of SystemJS usage there than in my TypeScript package's readme. Please ignore references to babel.json, because they only apply to my Babel package.

**Comment by mattiLeBlanc** [comment] 2016-02-06 06:45
Thanks for your reply! Really helpful.
I also found your angular2-now packages. Jeez, you have been busy! 
I am developing for a production environment so for the prototype I use your Typescript package and A1.4. But I am very interested in porting it to Angular2-now.
Not sure how long it takes for Angular2 to be released but it would be nice to start to know the syntax beforehand.
What would you reckon for a production project (financial business...can't crash).

**Comment by pbastowski** [comment] 2016-02-06 07:00
I can provide no guarantees :) However, in my team we are using the `angular2-now` package in several production apps (at an Airline company). None of these apps are mission critical, but at the same time, I haven't seen any bug reports from users that were traced back to the library itself. I also know it is being used in public production apps by others, such as a betting company. 

It is not that complex a library by design, as in, it does not try to implement all of Angular2's features. It aims at allowing you to use your existing Angular1 knowledge and to create new components with an Angular2-like syntax. The `@State` decorator makes it much easier to use `ui-router` in your app. Also, as you can see on the front page, we have good test coverage now around 90%. I am certainly going to use `angular2-now` for any Angular1 apps I build in the coming months.

So, I would say that your risks should be minimal. But, in the final analysis, you have to make your own judgement as to this library's fitness for production systems.

p.s. If you're not "married" to Angular1, then I would say that Angular2 beta is quite useable already.

**Comment by mattiLeBlanc** [comment] 2016-02-06 07:19
Okay, I am going to apply Angular2-now after the prototype demonstration (and after my holiday), which would be in a couple of weeks.
I really CAN'T wait to use Angular2. Definitely not married to version 1. I am in the nice position to actually introduce new techs and stacks. And I got a couple of colleagues who very happy to start using A2. 
However, as a contractor I have to advocate a new technology, so that if I leave I don't leave a legacy that people can't deal with or don't agree with.
But those things can be ironed out during my contract.
I am so exited!! :)

**Comment by pbastowski** [comment] 2016-02-06 07:23
Sounds like a plan. I'll close this issue then.

**Closed as completed by pbastowski** 2016-02-06 07:23 UTC
